version: "3"
services:
  database:
    image: postgres
    volumes:
      - database_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}-dev
  backend: 
    build: ./backend/
    ports: 
      - 80:3000
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 10; done; npm start'
    volumes:
      - ./backend:/usr/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@database/${DB_NAME}-dev
      NODE_ENV: dev
      PORT: 3000
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./frontend:/usr/app
    depends_on:
      - backend
volumes:
  database_dev: